spring.application.name=banking-platform
spring.datasource.url=jdbc:postgresql://localhost:5432/bankingdb
spring.datasource.username=banking_user
spring.datasource.password=banking_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

management.endpoints.web.exposure.include=health,info

spring.flyway.enable=true
spring.flyway.locations=classpath:db/migration

